project:
  type: website
  output-dir: docs
  execute-dir: project
website:
  title: "Emerging trends for raccoon in Europe"
  navbar:
    left:
      - href: dashboard.qmd
        text: Home
      - href: about_data.qmd
        text: About the Data
format:
  html:
    theme: flatly